### PR TITLE
MGDOBR-1047: Add [Renovate] prefix for PR created by Renovate bot

### PR DESCRIPTION
**Pull request by jomarko**
for more details: https://issues.redhat.com/browse/MGDOBR-1047

### CODE REVIEW

**Review by vpellegrino — APPROVED** [review]
Fine for me

**Review by kelvah — COMMENTED** [review]
Could we do the same by using the `labels` property in the renovate configuration?
See https://docs.renovatebot.com/configuration-options/#addlabels

**Comment by jomarko** [comment]
@kelvah that is good suggestion, I will adopt it

**Comment by jomarko** [comment]
@kelvah changes incorporated. PR refactored.

**Comment by kelvah** [comment]
> @kelvah changes incorporated. PR refactored.

Thanks @jomarko.

I see there's also a `prTitle` configuration option but it's deprecated. They discourage altering the PR title, see https://docs.renovatebot.com/configuration-options/#prtitle

**Comment by jomarko** [comment]
@kelvah yes, I saw that, but it seemed to me as not fit for our use case. As you mention, they discourage from changing title. that way

**Comment by kelvah** [comment]
@jomarko I'm not sure if they are suggesting to avoid altering the pr title in general. I didn't find anything else on the matter by the way. let's see what happens :)

**Review by kelvah — APPROVED** [review]

**Pull request merged**
