### PR TITLE
MGDOBR-671: Plug SE instance creation to APIs

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/MGDOBR-671

### CODE REVIEW

**Review by manstis — APPROVED** [review]

**Review by jomarko — COMMENTED** [review]
Thank you for a PR @kelvah 

Two observations/questions from me:
- Is the 'Name already exists' the only negative scenario that can currently happen?
- Once I created instance, waited until it is in state 'Ready', then I tried pagination. The issue is, firstly old page was loaded and then correct re-render was done. See my video https://issues.redhat.com/secure/attachment/12717869/create%20and%20list.webm. Not sure if it is related to your changes. If not, probably bets is to report a separate jira?

**Comment by kelvah** [comment]
> * Is the 'Name already exists' the only negative scenario that can currently happen?

Besides a catastrophic error 500 (which we'll handle [here](https://issues.redhat.com/browse/MGDOBR-715)), the "already existing name" is the only error that can happen now.

There will be another possible error when hitting bridges quota limit for the user account. But it's too early for that, we have to wait for the API to support this type of check. 

> * Once I created instance, waited until it is in state 'Ready', then I tried pagination. The issue is, firstly old page was loaded and then correct re-render was done. See my video https://issues.redhat.com/secure/attachment/12717869/create%20and%20list.webm. Not sure if it is related to your changes. If not, probably bets is to report a separate jira?

Thanks for reporting it. I smell a mocked api failure. I'll look into it.

**Comment by kelvah** [comment]
> * Once I created instance, waited until it is in state 'Ready', then I tried pagination. The issue is, firstly old page was loaded and then correct re-render was done. See my video https://issues.redhat.com/secure/attachment/12717869/create%20and%20list.webm. Not sure if it is related to your changes. If not, probably bets is to report a separate jira?


After trying to reproduce it, this looks really similar to what I found [here](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/41#discussion_r870434797). There's already a ticket for it [here](https://issues.redhat.com/browse/MGDOBR-720)

**Review by vpellegrino — APPROVED** [review]
Ok for me, @kelvah

**Review by sjamboro — COMMENTED** [review]
Is it the desired behaviour:

1. Press F5 on the Instances list page - the new instance disappears.
2. The instance detail page shows "Instance one" instad of the new name.

It seems that the SE instance creation is not pernament. Is this JIRA only about the new row in the table?

**Comment by kelvah** [comment]
> Is it the desired behaviour:
> 
> 1. Press F5 on the Instances list page - the new instance disappears.
> 2. The instance detail page shows "Instance one" instad of the new name.
> 
> It seems that the SE instance creation is not pernament. Is this JIRA only about the new row in the table?

Yes, it's the expected behavior when using the mocked APIs. New data is lost when refreshing.

If you want you can run the app against the real APIs on the dev environment by running `npm run start`. Just remember to not create too much instances there, or eventually delete them using swagger afterwards.

**Comment by sjamboro** [comment]
> > Is it the desired behaviour:
> > 
> > 1. Press F5 on the Instances list page - the new instance disappears.
> > 2. The instance detail page shows "Instance one" instad of the new name.
> > 
> > It seems that the SE instance creation is not pernament. Is this JIRA only about the new row in the table?
> 
> Yes, it's the expected behavior when using the mocked APIs. New data is lost when refreshing.
> 
> If you want you can run the app against the real APIs on the dev environment by running `npm run start`. Just remember to not create too much instances there, or eventually delete them using swagger afterwards.

Thanks, I guess that the reason is mocked data.

**Review by sjamboro — APPROVED** [review]
LGTM ... the name validation works, the new instance is created and shown by table.

**Pull request merged**
