### PR TITLE
[No-Jira] Skip checks of 'non deterministic' updates in 'Status' popo…

### PR DESCRIPTION
**Pull request by jomarko**
…ver in Dev environment

This is an alternative for #226

### CODE REVIEW

**Comment by jomarko** [comment]
Attempt No#1 PASSED.

**Comment by jomarko** [comment]
Attempt No#3 FAILED the login phase.
the 'Create a SE instance' Modal -- Submit and expect error -- before each hook (failed)

**Comment by jomarko** [comment]
Attempt No#4 PASSED.

**Comment by jomarko** [comment]
Attempt No#5 PASSED.

**Review by kelvah — APPROVED** [review]
LGTM :ok_hand: 
Thanks @jomarko for considering feedback and for taking care of exploring alternative solutions. Great job!

**Review by sjamboro — COMMENTED** [review]
In this case I miss validation that the popover is present on the dev and contains all appropriate states. I think that the solution from #226 is better for me. 

The approach of #226 has these benefits:
- it tries to validate all steps on dev and mocked environment
- it defines a condition when the environment is not deterministic
- IMO it is more readable than definition what can run on DEV and what will run on MOCKED

The approach of #226 has this negative:
- we need to define the condition well to not mask the real problem

**Comment by jomarko** [comment]
Taking into account https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/230#pullrequestreview-1149098547

I will close #230

**Pull request closed without merging**
