### PR TITLE
MGDOBR-742: Set up config context and update auth context

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/MGDOBR-742

### CODE REVIEW

**Review by manstis — APPROVED** [review]
LGTM 👍

**Comment by kelvah** [comment]
Cypress smoke tests are failing. They are also randomly failing locally but I can't figure out why. :thinking:

**Comment by jomarko** [comment]
@kelvah thank you for raising a point about test instability. I created a stabilization PR here https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/64/files

**Review by vpellegrino — APPROVED** [review]
LGTM, thanks @kelvah

**Comment by jomarko** [comment]
Update, my stabilization PR seems not working in CI :(. Locally it fixed the test, please ignore it for now.

**Comment by sjamboro** [comment]
@kelvah the failing test does not assert any important functionality. Other tests succeed.

**Comment by kelvah** [comment]
Should we merge then? @jomarko or @sjamboro, do you want to add your review?

**Review by sjamboro — APPROVED** [review]
LGTM thanks @kelvah 
I hope that the test is fixed on the main branch. Please rebase PR before you merge it.

**Comment by kelvah** [comment]
Tests are passing now. Merging.

**Pull request merged**
