### PR TITLE
NO-JIRA: fix SDK <-> API github action

### PR DESCRIPTION
**Pull request by sjamboro**
As it describes in github action. I have run:
```
scripts]$ ./fetch_openapi.sh
scripts]$ ./generate_openapi_client.sh
```

And I have commit all changes.

### CODE REVIEW

**Comment by manstis** [comment]
As the CI build shows, it is not as simple as regenerating the files as it can (and does in this case) lead to a need to refactoring the UI too.

**Comment by jomarko** [comment]
Removing my approval reading @manstis comment above. Thank you for spotting.

**Comment by sjamboro** [comment]
@manstis uff ... I can see it now :(

**Comment by sjamboro** [comment]
I close this PR request because the fix of the compatibility of SDK and Openapi requires more changes.

**Pull request closed without merging**
