### PR TITLE
MGDOBR-530: Fix missing explicit function types

### PR DESCRIPTION
**Pull request by jomarko**
For more details, see the jira:
- https://issues.redhat.com/browse/MGDOBR-530

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis @kelvah @vpellegrino hello, this PR is ready for review, I am interested especially in your opinion for lines with `JSX.Element`

**Comment by vpellegrino** [comment]
@jomarko I think that for React function components, the right type is `FunctionComponent`, with an optional type parameter in case they have props.

**Comment by vpellegrino** [comment]
> @jomarko I think that for React function components, the right type is `FunctionComponent`, with an optional type parameter in case they have props.

Ok, I performed further research. 
It seems that `JSX.Element` is fine too. Instead `React.FC` is discouraged.

Please have a look.
https://github.com/typescript-cheatsheets/react/blob/main/README.md#section-2-getting-started

**Review by kelvah — APPROVED** [review]
Approving. +1 for JSX:Element instead of the cursed React.FC.

**Comment by kelvah** [comment]
> Ok, I performed further research. It seems that `JSX.Element` is fine, instead `React.FC` is discouraged.
> 
> Please have a look. https://github.com/typescript-cheatsheets/react/blob/main/README.md#section-2-getting-started

We had a similar discussion in the jira ticket. Are we still adding the jira link to PR descriptions?

**Comment by jomarko** [comment]
@kelvah thank you, I added the jira link into description. @manstis @vpellegrino may I ask you to provide 'official' review?

**Review by vpellegrino — APPROVED** [review]
LGTM, thanks @jomarko

**Review by manstis — APPROVED** [review]
IIUC we're enforcing adding return types.. LGTM :+1:

**Pull request merged**
