### PR TITLE
MGDOBR-1133: Insert cookies to avoid the cookies popover form

### PR DESCRIPTION
**Pull request by sjamboro**
https://issues.redhat.com/browse/MGDOBR-1133

I will run GHA 15 times to be sure that the popover form is not occured.

Results:
**Smart Events UI :: Dev :: Quality Checks -> 12/15 runs passed**
A. first failure should be corrected by using "Domain: .redhat.com" - related with this issue
B. not sure why the visit command does not redirect page to SSO - not sure if it is related
C. Unexpected failure -> UI is not expected ... need investigation - this shouldnt be related with this issue

**Smart Events UI :: Mocked :: Quality Checks -> 14/15 runs passed**
A. Error during loading the page - not related with code

**Smart Events UI :: Build -> 15/15 runs passed**

### CODE REVIEW

**Comment by sjamboro** [comment]
Run no. 1: passed
image

image

**Comment by sjamboro** [comment]
Run no. 2: passed
image

image

**Comment by sjamboro** [comment]
Run no. 3: failed

image

**Comment by sjamboro** [comment]
Run no. 4: passed
image

**Comment by sjamboro** [comment]
Run no. 5: passed


image

**Review by jomarko — APPROVED** [review]
Thank you @sjamboro

**Comment by sjamboro** [comment]
Run no. 6: passed
image

image

**Comment by sjamboro** [comment]
Run no. 7: passed
image

image

**Comment by sjamboro** [comment]
Run no. 8: passed
image

image

**Comment by sjamboro** [comment]
Run no. 9: passed
image

image

**Comment by sjamboro** [comment]
Run no. 10: failed
image

image

image

**Comment by sjamboro** [comment]
Run no. 11: passed
image

image

**Comment by sjamboro** [comment]
Run no. 14: failed
image

image

image

```
<failure message="Timed out retrying after 10000ms: Expected to find element: `#username-verification`, but never found it. Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `the 'Create a SE instance' ...`" type="AssertionError">
<![CDATA[ AssertionError: Timed out retrying after 10000ms: Expected to find element: `#username-verification`, but never found it. Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `the 'Create a SE instance' ...` at Context.eval (webpack:///./support/commands.ts:65:5) ]]>
</failure>
```

**Comment by sjamboro** [comment]
Run no. 15: failed
image

image

![image](https://user-images.githubusercontent.com/1536609/201746625-f92d
```
<testcase name="Basic Elements "before each" hook for "The navigation panel is visible"" time="0.000" classname=""before each" hook for "The navigation panel is visible"">
<failure message="The following error originated from your application code, not from Cypress. > Error while retrieving the list of Smart Event instances. When Cypress detects uncaught errors originating from your application it will automatically fail the current test. This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event. https://on.cypress.io/uncaught-exception-from-application Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Basic Elements`" type="Error">
<![CDATA[ Error: The following error originated from your application code, not from Cypress. > Error while retrieving the list of Smart Event instances. When Cypress detects uncaught errors originating from your application it will automatically fail the current test. This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event. https://on.cypress.io/uncaught-exception-from-application Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Basic Elements` at eval (webpack-internal:///./src/app/Instance/InstancesListPage/InstancesListPage.tsx:108:19) at invokePassiveEffectCreate (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23482:20) at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:14) at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3994:16) at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4056:31) at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23569:9) at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:468:12) at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11276:10) at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23442:14) at performSyncWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22264:3) ]]>
</failure>
</testcase>
```2287-1c03-40fb-99db-6544960e54d4.png)

**Review by kelvah — APPROVED** [review]
I've run the tests locally against `dev` a dozen of times and I confirm the cookie dialog is gone.
Thanks @sjamboro.

I wasn't able to reproduce the error of runs n. 14 and n. 15 (`Timed out retrying after 10000ms: Expected to find element: #username-verification`). It seems that for some reason the user was already logged in when the login command started, so the login form was not there (or maybe the login command run twice?). Let's see if it happens again. We can eventually address it in another ticket.

**Pull request merged**
