### PR TITLE
MGDOBR-1119:Allow the bridge instance to edit in case of instance is in FAILED status

### PR DESCRIPTION
**Pull request by ppadti**
JIRA: https://issues.redhat.com/browse/MGDOBR-1119

Steps to test it (on chrome):

- Create a bridge instance with Incorrect parameters to enter into Failed state.
- Then it will allow to edit the bridge instance.
- Also, the status label of the bridge is visible on the Instance Page.

### CODE REVIEW

**Comment by manstis** [comment]
I tried to test manually with `main` and `npm run start`.

When creating a new Instance with name `b1` and a Webhook URL `https://webhook.site/${env.webhook.site.uuid}` the dialog did not close and there was an error in the JavaScript console:

image

**Comment by vpellegrino** [comment]
> https://webhook.site/${env.webhook.site.uuid}

hi @manstis, it seems that the issue is also present on the `main` branch and is about the 402 HTTP error returned by API. I think it is expected. Is it not?

**Comment by kelvah** [comment]
That's the error for the quota limit. The dialog is hanging because it's not yet managed (it will be with [MGDOBR-1181](https://issues.redhat.com/browse/MGDOBR-1181))

It seems our openbridge organization has reached the quota limit for bridges on dev. I guess we have to clean up old bridges there.

**Review by vpellegrino — APPROVED** [review]
The PR looks good to me. Thank you @ppadti

**Review by manstis — APPROVED** [review]
Code change LGTM :+1:

**Review by kelvah — APPROVED** [review]
LGTM. :ok_hand:

**Review by jomarko — COMMENTED** [review]
Thank you for a PR. I have observed this inappropriate information in our application now.

Following instructions from the PR title, I prepared myself a bridge instance in a failed state. Then I opened this failed bridge instance detail page. That allows user to start creating a processor. Once user tries to submit processor, this dialogue is shown, however it is a semi correct.

- user is not able to create a processor for a failed bridge instance - ok
- explanation why it is not possible - **not ok**

Screenshot from 2022-10-31 11-32-37

**Comment by kelvah** [comment]
> Thank you for a PR. I have observed this inappropriate information in our application now.

@jomarko good catch! I think the APIs should allow the creation of a processor inside a bridge that failed because of the EH configuration. I'm inclined to disable the "create processor" button for failed bridges for now. It's a big topic and I'm not sure we are going to address it soon. @manstis wdyt?

**Comment by manstis** [comment]
> > Thank you for a PR. I have observed this inappropriate information in our application now.
> 
> @jomarko good catch! I think the APIs should allow the creation of a processor inside a bridge that failed because of the EH configuration. I'm inclined to disable the "create processor" button inside failed bridges for now. It's a big topic and I'm not sure we are going to address it soon. @manstis wdyt?

I think your proposal @kelvah is reasonable... the backend does not support creating Processors for FAILED Bridges (which should be the case if the EH Processor FAILED as it should lead to the Bridge being FAILED too). This whole "life cycle" could do with a review (for v2!!) really.

**Comment by jomarko** [comment]
@kelvah ok, so please link jira, where this will be addressed and I can approve

**Comment by kelvah** [comment]
@jomarko Here's the ticket [MGDOBR-1203](https://issues.redhat.com/browse/MGDOBR-1203)

**Review by jomarko — APPROVED** [review]

**Pull request merged**
