### PR TITLE
MGDOBR-544: Various refinements

### PR DESCRIPTION
**Pull request by kelvah**
### Follows #22 

https://issues.redhat.com/browse/MGDOBR-544

With this PR I'm addressing minor changes to improve the overall demo of the static UI.
It's mostly about improving consistency of names, statuses and spacing across different pages. See jira link for more info.

### CODE REVIEW

**Review by vpellegrino — APPROVED** [review]
It looks absolutely good to me.
Thank you @kelvah

**Review by manstis — APPROVED** [review]
The third commit LGTM :+1:

**Comment by jomarko** [comment]
@kelvah please rebase the PR

**Comment by kelvah** [comment]
> @kelvah please rebase the PR

@jomarko Done

**Review by jomarko — COMMENTED** [review]
@kelvah thank you for the PR.

Is it intentional we have just one status highlighted with icon?

Shouldn't we have sth like?

https://github.com/kelvah/sandbox-ui/pull/2

Screenshot from 2022-04-21 08-53-20

**Comment by kelvah** [comment]
> @kelvah thank you for the PR.
> 
> Is it intentional we have just one status highlighted with icon?
> 
> Shouldn't we have sth like?
> 
> [kelvah#2](https://github.com/kelvah/sandbox-ui/pull/2)
> 

@jomarko I just added basic labels for now.

The plan is to switch to the kafka [label](https://redhat-developer.github.io/app-services-ui-components/?path=/story/kafka-kafka-instance-status-components-status-label-status-label--all-statutes-at-once) + [popover](https://redhat-developer.github.io/app-services-ui-components/?path=/story/kafka-kafka-instance-status-components-status-popover-status-popover--pending-status) (probably cloning them) as soon as [MGDOBR-455](https://issues.redhat.com/browse/MGDOBR-455) is done

**Review by jomarko — APPROVED** [review]

**Pull request merged**
