### PR TITLE
MGDOBR-1196: "Create bridge" dialog hangs after API unexpected managed errors

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/MGDOBR-1196

Steps to test:
- run the app against mocked APIs with `npm run start:mocked`
- click on `Create Smart Events Instance`
- enter a name containing `error-test`, like `bridge error-test`
- submit the form by clicking on `Create Smart Events Instance`
- after the API request is done, the dialog exits its loading status and the generic error alert appears on top

### CODE REVIEW

**Review by manstis — APPROVED** [review]
LGTM :+1:

**Comment by jomarko** [comment]
Do I understand correctly this is an expected state @kelvah ?
Screenshot from 2022-11-01 08-42-35

**Comment by kelvah** [comment]
> Do I understand correctly this is an expected state @kelvah ? Screenshot from 2022-11-01 08-42-35

@jomarko That's correct. It's an unexpected error that shouldn't happen but we have to cover it anyway.

**Review by jomarko — APPROVED** [review]
Fine for me, however I think, we should add a test https://github.com/kelvah/sandbox-ui/pull/7

**Pull request merged**
