### PR TITLE
MGDOBR-990: Refresh Smart Events Instance Details, while the drawer is open

### PR DESCRIPTION
**Pull request by ppadti**

### CODE REVIEW

**Comment by ppadti** [comment]
for more details: 
https://issues.redhat.com/browse/MGDOBR-990

**Review by kelvah — APPROVED** [review]
Thank you @ppadti, It looks good to me :+1: 

Only a small observation, could you please update the PR title using the same title of the JIRA ticket?
With this PR you are _refreshing_ the instance details, not just _displaying_ them.

**Review by jomarko — APPROVED** [review]
I have tried manually that the changes work. I am approving. However it would be good to add some unit test probably.

Thank you @ppadti

**Comment by kelvah** [comment]
> I have tried manually that the changes work. I am approving. However it would be good to add some unit test probably.

@jomarko `InstanceListPage` is a "container" component dealing with APIs, I would keep it covered only with cypress tests. We could add a test there to check that the drawer content is properly refreshed over time for example.

But sure we should improve unit test coverage too. The `InstanceDetails` component for example lacks unit tests completely.

**Comment by jomarko** [comment]
@kelvah thank you, I have created a separate ticket for cypress test https://issues.redhat.com/browse/MGDOBR-1087

**Pull request merged**
