### PR TITLE
MGDOBR-504: Rename i18n dictionary from open bridge to smart events

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/MGDOBR-504

### CODE REVIEW

**Review by manstis — APPROVED** [review]
LGTM :+1:

**Review by vpellegrino — APPROVED** [review]
LGTM

**Review by jomarko — COMMENTED** [review]
@kelvah please fix the conflicting file

**Comment by kelvah** [comment]
> @kelvah please fix the conflicting file

@jomarko fixed!

**Review by jomarko — APPROVED** [review]
Failing test is a known issue with initial cookies consent dialogue. Manual check didn't reveal some errors or warnings in browser console. Approving.

**Pull request merged**
