### PR TITLE
[NoJira] Archive html on test failue ucing cyclope

### PR DESCRIPTION
**Pull request by jomarko**
In the CI we spot some random failures caused by a popover element shown in non deterministic way. That is why we would like to archive the produced html on test failure.

### CODE REVIEW

**Comment by sjamboro** [comment]
@jomarko it is really strange that all tests passed?

**Comment by vpellegrino** [comment]
@Srihari1192 or @sjamboro, who can resume this work? I think it was useful from a stability/reporting perspective.
Please, let me know.

**Comment by sjamboro** [comment]
@vpellegrino I agree with you that such functionality is usefull. This PR was created but it does not work as the cyclope README says. I can take a look at it. Do we close this PR from jomarko fork? @Srihari1192 Should I create a JIRA for this issue?

**Comment by vpellegrino** [comment]
@sjamboro I agree with you on creating a Jira and closing this PR.
Thank you for taking care.

**Comment by Srihari1192** [comment]
@sjamboro Sure. We can close this and create a Jira.
Thanks

**Comment by jomarko** [comment]
@Srihari1192 @sjamboro FYI, closing this as requested above.

**Pull request closed without merging**
