### PR TITLE
MGDOBR-677: Plug SE instance deletion to APIs

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/MGDOBR-677

It's only possible to delete SE Instances with no processors inside at the moment.

So, to test this PR, you should try to delete instances with and without processors inside. It's possible to delete instances from the table in the home screen and from the "actions" dropdown inside the instance detail page.

If you run the app against the mocked APIs, "Instance one" is the only one with processors, while the others have none.

### CODE REVIEW

**Review by vpellegrino — APPROVED** [review]
The PR overall looks good to me.
Good job @kelvah

**Review by manstis — APPROVED** [review]
LGTM :+1:

**Comment by kelvah** [comment]
@sjamboro we are missing your review :slightly_smiling_face: 
adding also @jomarko who maybe has some time to look at it.

**Review by jomarko — APPROVED** [review]
Thank you @kelvah

**Review by sjamboro — APPROVED** [review]
New functionality works without problems for common users. I reported here one situation when I forgot that I have already deleted the bridge instance. InstancePage is not pooling and I am able to see this page after deletion (copied address). I believe that it can be solved by different JIRA.

Feel free to merge this PR.

**Pull request merged**
