### PR TITLE
MGDOBR-854: API Root Context Path should be /api/smartevents_mgmt/v1

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/MGDOBR-854

Depends on https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/912 for backend changes.

This is a search/replace on the code base.

### CODE REVIEW

**Comment by kelvah** [comment]
> @kelvah @vpellegrino @jomarko Have I done something wrong on this repository?
> 
> I don't understand the "Smart Events UI :: Build / run-all-checks (pull_request)" build failure.

@manstis I see you've already solved the issue, whatever it was :slightly_smiling_face:

**Comment by manstis** [comment]
The "SDK <-> OpenApi" check fails as the new `rhose-api.yaml` file does not exist on `main` in the `sandbox` repository yet. This PR has the generated SDK updated based on the new root context.

**Comment by manstis** [comment]
@kelvah @vpellegrino @jomarko This PR is now ready for your review.

**Comment by kelvah** [comment]
> @kelvah @vpellegrino @jomarko This PR is now ready for your review.

@manstis Shouldn't we deploy the changes to `dev` first?

**Comment by manstis** [comment]
> @manstis Shouldn't we deploy the changes to `dev` first?

IDK you tell me :smile: 

The back-end change is on `main` so I'd assume the front-end change could be applied to `main` too?

If you'd rather wait until the back-end is on `dev` I can wait.. but you can still approve :+1:

**Review by vpellegrino — APPROVED** [review]
Looks good to me, thank you @manstis

**Comment by kelvah** [comment]
> The back-end change is on `main` so I'd assume the front-end change could be applied to `main` too?
> 
> If you'd rather wait until the back-end is on `dev` I can wait.. but you can still approve +1

@manstis If we merge this PR now, the UI on `main` will break when running `npm run start`.

So yes, I would merge this only after the API changes are deployed. Also because we are not able to test it against real APIs atm.

**Comment by vpellegrino** [comment]
@manstis @kelvah it seems that API changes are deployed, so I'm going to merge this PR

**Pull request merged**
