### PR TITLE
MGDOBR-873: Verify the new kafka topic action is properly supported by the UI

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/MGDOBR-873

Checking the new kafka topic sink. No issues found. Just updating the corresponding mock.

### CODE REVIEW

**Review by manstis — APPROVED** [review]
Based on [this](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/blob/main/processor/configuration/src/main/resources/schemas/actions/kafka_topic_sink_0.1.json) LGTM.

**Review by vpellegrino — APPROVED** [review]
LGTM, thanks @kelvah

**Review by jomarko — COMMENTED** [review]
Thank you @kelvah . My only question is only about the titles. Thinking how to help user to understand the form as soon as possible. So my question is :
- `title: "Broker URL"` vs `title: "Kafka Broker URL"`
- `title: "Client Id`, vs `title: "Kafka Client Id"`
- `title: "Client Secret`, vs `title: "Kafka Client Secret"`

What is your opinion?

**Comment by kelvah** [comment]
> Thank you @kelvah . My only question is only about the titles. Thinking how to help user to understand the form as soon as possible. So my question is :
> 
> * `title: "Broker URL"` vs `title: "Kafka Broker URL"`
> * `title: "Client Id`, vs `title: "Kafka Client Id"`
> * `title: "Client Secret`, vs `title: "Kafka Client Secret"`
> 
> What is your opinion?

@jomarko Uhm I think having "Kafka" in every field name could be repetitive. The "Kafka Topic" name of the action should make clear enough they are all related to kafka.

Anyway, as soon as we can make RHOSE working in the qa env and share its link, we can ask for a review of all labels/tooltips from UX and content designers.

**Review by jomarko — APPROVED** [review]
Ok, I understand my proposal is not being applied.

**Pull request merged**
