### PR TITLE
MGDOBR-752: Provide links to the SE Instance detail page only when the Instance is "ready"

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/MGDOBR-752

Steps to test it:
- create a new SE instance
- wait for it to appear in the list
- there should be no link on its name until it reaches the `ready` status

### CODE REVIEW

**Review by manstis — APPROVED** [review]
Super simple (and effective).

:superhero:

**Review by vpellegrino — APPROVED** [review]
Looks good to me

**Review by sjamboro — CHANGES_REQUESTED** [review]
Hi @kelvah, can you put unit test(s) here? If there might be a problem accessing an instance before it is ready, we should check it.

The expectation of MGDOBR-752 was fulfilled.

On InstancePage, we could disable the "Create Procesor" button or the "Delete" action . I am not sure if a user has access to the ID of the new instance (via REST API).

**Comment by sjamboro** [comment]
> > Hi @kelvah, can you put unit test(s) here? If there might be a problem accessing an instance before it is ready, we should check it.
> 
> @sjamboro I think we agreed to cover data-fetching components with E2E tests only.
> 
> I could agree this component has grown a bit too much and we could consider splitting it further between data fetching logic and templating.

I have created this issue https://issues.redhat.com/browse/MGDOBR-756. We can discuss the final location later. I understand that it is a nonsence to test it in both test suites (`test` and `test:it`). Currently both test suites are running in PR checks. IMHO the component test performs it quicker than a cypress test.

> 
> > On InstancePage, I am not sure if a user has access to the ID of the new instance (via REST API). Can he or she create own link? If yes, we could disable the "Create Procesor" button or the "Delete" action .
> 
> This means the user is manipulating the UI beyond what is allowed. In any case trying to create processors in this way will still result in a API failure. If we want to take care of this scenario, We could probably prevent direct access to the instance details page, maybe doing a redirection.

Such situation is not allowed but possible. The redirection sounds good. Maybe the simplier way is just show name and status plus some info warning about the situation. You can solve it separately.

> 
> > On InstanceListPage, is possible to delete an instance when the state is "Accepted" or "Provisioning"?
> 
> No, it's not possible. It's handled in my other PR #52
It is on my TODO list :) I will take a look at it

**Review by sjamboro — APPROVED** [review]
LGTM

**Pull request merged**
