### PR TITLE
MGDOBR-1117: Status label of bridges and modified_at support

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/MGDOBR-1117

Steps to test it:
1. `npm run start:mocked`
2. click on the bridge `Instance one` and edit its error handling configuration
3. save the change
4. after being redirected to the bridge list, `Instance one` status is `Creating` and the message `This is taking longer than expected.` is not shown anymore

### CODE REVIEW

**Review by manstis — APPROVED** [review]
LGTM :+1:

**Comment by manstis** [comment]
I checked and this is (1) consistent with elsewhere, (2) the last remaining place `requestedAt` is not handled correctly.

**Review by vpellegrino — APPROVED** [review]
LGTM

**Review by jomarko — COMMENTED** [review]
@kelvah thank you for PR. To me it seems to work properly. However I think some test should be added. See my PR https://github.com/kelvah/sandbox-ui/pull/6

**Comment by kelvah** [comment]
@jomarko good job :+1:
I've merged your PR.

**Review by jomarko — APPROVED** [review]
Thank you @kelvah

**Pull request merged**
