### PR TITLE
MGDOBR-712 - [UI] added test for verifying processor header details

### PR DESCRIPTION
**Pull request by ChughShilpa**
https://issues.redhat.com/browse/MGDOBR-712

### CODE REVIEW

**Review by jomarko — APPROVED** [review]
Looks ok to me, thank you. Adding also @sjamboro as reviewer.

**Comment by sthundat** [comment]
@ChughShilpa ,
Can you provide Jira link on the description?

**Comment by ChughShilpa** [comment]
> @ChughShilpa , Can you provide Jira link on the description?

Done.. will be careful next time

**Comment by ChughShilpa** [comment]
@jomarko 
One check is failed.
and i checked this got failed in all open PRs.. Is there any particular reason?
I did check the details but couldn't get the reason

**Comment by jomarko** [comment]
yes, the 'SDK <-> Openapi compatibility check' fail is expected. We are currently in state, when sandbox and sandbox-ui uses non-synced coppies of rhose-api.yaml files. Manual sync is needed, but it is not trivial. Currently it is not worth to invest into this 'SDK <-> Openapi compatibility check' as there is ongoing work in official RHOSE SDK, that will be consumed by sandbox-ui.

@ChughShilpa

**Comment by ChughShilpa** [comment]
> yes, the 'SDK <-> Openapi compatibility check' fail is expected. We are currently in state, when sandbox and sandbox-ui uses non-synced coppies of rhose-api.yaml files. Manual sync is needed, but it is not trivial. Currently it is not worth to invest into this 'SDK <-> Openapi compatibility check' as there is ongoing work in official RHOSE SDK, that will be consumed by sandbox-ui.
> 
> @ChughShilpa

Thanks @jomarko for the explanation

**Review by sjamboro — APPROVED** [review]
LGTM ... Thank you. Do not forget to rebase on the top of the main branch before you merge it as "Squash and merge" 
image

**Pull request merged**
