### PR TITLE
[no-jira] Fix npm vulnerabilities

### PR DESCRIPTION
**Pull request by jomarko**
npm install was returning:
```
jomarko@localhost sandbox-ui (main)$ npm install

> smartevents-ui@0.0.1 prepare
> husky install

husky - Git hooks installed

added 13 packages, removed 61 packages, changed 5 packages, and audited 1468 packages in 8s

184 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

This PR contains changes done by `npm audit fix`

### CODE REVIEW

**Review by kelvah — COMMENTED** [review]
Thanks @jomarko for looking into this issue.

I think Renovate should take care of security updates too. Probably there's something missing in our setup.

I'm mentioning it because it's likely Renovate will try first to update the packages depending on the vulnerable ones before resorting to the "hard way", fixing the lock file.

**Comment by jomarko** [comment]
@kelvah  thank you for investigation and explanation. I see some alerts now here, on `Security` tab https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/security/dependabot, however it seems `Renovate` didn't create any PR related to it.

Maybe we can at least fix vulnerability via the `Security` tab instead of my PR?

**Review by sjamboro — COMMENTED** [review]
It is fine that the audit command fixed the problem. Both quality checks show:
```
> smartevents-ui@0.0.1 prepare
> husky install

husky - Git hooks installed

added [14](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/actions/runs/3321763951/jobs/5489856729#step:4:15)67 packages, and audited 1468 packages in 1m

184 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

IIUC the renovate should take care of it and it did not work. I agree that we need to automate it.

**Comment by kelvah** [comment]
> Maybe we can at least fix vulnerability via the `Security` tab instead of my PR?

@jomarko I wouldn't mix dependabot and renovate PRs. Let's use your fix for now and see if renovate will trigger PRs for future alerts.

**Review by kelvah — APPROVED** [review]

**Review by vpellegrino — APPROVED** [review]

**Pull request merged**
